# Generated by Django 5.1.6 on 2025-02-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('down_votes', models.ManyToManyField(related_name='blog_down_votes', to=settings.AUTH_USER_MODEL)),
                ('up_votes', models.ManyToManyField(related_name='blog_up_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
