# Generated by Django 5.1.6 on 2025-02-09 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='down_votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='up_votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
